"""
Utility Functions for Disease Prediction System  (Real Dataset)
===============================================================
Loads trained artefacts at import time and exposes helper functions
for the Flask backend.
"""

import os
import pickle

import numpy as np
from PIL import Image

# ──────────────────────────────────────────────────────────────────────
# Paths
# ──────────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ──────────────────────────────────────────────────────────────────────
# Load metadata generated by the training scripts
# ──────────────────────────────────────────────────────────────────────

# -- Symptom metadata (populated by train_symptom_model.py) --
_meta_path = os.path.join(BASE_DIR, "symptom_meta.pkl")
if os.path.exists(_meta_path):
    with open(_meta_path, "rb") as _f:
        _META = pickle.load(_f)
    SYMPTOM_LIST: list[str]    = _META["symptoms"]      # sorted canonical list
    SEVERITY_DICT: dict        = _META["severity"]       # symptom → weight
    DESCRIPTION_DICT: dict     = _META.get("descriptions", {})
    PRECAUTION_DICT: dict      = _META.get("precautions", {})
else:
    # Fallback minimal list (used if model not yet trained)
    SYMPTOM_LIST = [
        "itching", "skin_rash", "continuous_sneezing", "shivering", "chills",
        "joint_pain", "stomach_pain", "acidity", "vomiting", "fatigue",
        "cough", "high_fever", "headache", "nausea", "loss_of_appetite",
        "muscle_pain", "chest_pain", "dizziness", "sore_throat",
        "shortness_of_breath", "swelling", "weight_loss", "blurred_vision",
        "sweating", "diarrhea", "runny_nose", "congestion", "back_pain",
        "stiff_neck", "yellowing_of_eyes",
    ]
    SEVERITY_DICT = {}
    DESCRIPTION_DICT = {}
    PRECAUTION_DICT = {}

# -- Image classes (populated by train_image_model.py) --
_img_cls_path = os.path.join(BASE_DIR, "image_classes.pkl")
if os.path.exists(_img_cls_path):
    with open(_img_cls_path, "rb") as _f:
        IMAGE_CLASSES: list[str] = pickle.load(_f)
else:
    IMAGE_CLASSES = [
        "skin_rash", "acne", "eczema", "psoriasis", "melanoma",
        "eye_infection", "tongue_disease", "wound_infection",
        "xray_abnormal", "healthy",
    ]

IMAGE_SIZE = (224, 224)


# ──────────────────────────────────────────────────────────────────────
# Symptom Helpers
# ──────────────────────────────────────────────────────────────────────

def get_symptom_list() -> list[str]:
    """Return the canonical symptom list used during training."""
    return SYMPTOM_LIST


def get_image_classes() -> list[str]:
    """Return the ordered image class list used during training."""
    return IMAGE_CLASSES


def encode_symptoms(selected_symptoms: list[str]) -> np.ndarray:
    """
    Encode selected symptoms into a numeric feature vector of length
    ``len(SYMPTOM_LIST)``.  Values are severity weights (or 1 if unknown).
    """
    vector = np.zeros(len(SYMPTOM_LIST), dtype=np.float32)
    sym_to_idx = {s: i for i, s in enumerate(SYMPTOM_LIST)}

    for symptom in selected_symptoms:
        clean = symptom.strip().lower().replace(" ", "_").replace("__", "_")
        if clean in sym_to_idx:
            weight = SEVERITY_DICT.get(clean, 1)
            vector[sym_to_idx[clean]] = weight
    return vector


def get_disease_description(disease: str) -> str:
    """Return a textual description for the disease, or empty string."""
    return DESCRIPTION_DICT.get(disease, "")


def get_disease_precautions(disease: str) -> list[str]:
    """Return a list of precaution strings for the disease."""
    return PRECAUTION_DICT.get(disease, [])


# ──────────────────────────────────────────────────────────────────────
# Image Helpers
# ──────────────────────────────────────────────────────────────────────

def preprocess_image(filepath: str, target_size: tuple = IMAGE_SIZE) -> np.ndarray:
    """
    Load, resize, normalise to [0, 1], add batch dimension.
    Returns shape ``(1, 224, 224, 3)``.
    """
    img = Image.open(filepath).convert("RGB")
    img = img.resize(target_size, Image.LANCZOS)
    arr = np.array(img, dtype=np.float32) / 255.0
    return np.expand_dims(arr, axis=0)


def _extract_simple_features(filepath: str) -> np.ndarray:
    """
    Simple sklearn-compatible feature extraction without torch.
    Extracts color histograms, statistics, and texture features.
    Returns a 1-D float32 array of shape (1280,) for compatibility.
    """
    img = Image.open(filepath).convert("RGB")
    img = img.resize((224, 224), Image.LANCZOS)
    arr = np.array(img, dtype=np.float32) / 255.0
    img.close()
    
    features = []
    
    # Per-channel statistics (3 channels × 4 stats = 12)
    for c in range(3):
        ch = arr[:, :, c]
        features.extend([ch.mean(), ch.std(), ch.min(), ch.max()])
    
    # Color histograms (3 channels × 64 bins = 192)
    for c in range(3):
        hist, _ = np.histogram(arr[:, :, c].flatten(), bins=64, range=(0, 1))
        features.extend(hist / hist.sum())
    
    # Spatial grid features (8×8 grid, 3 channels = 192)
    for c in range(3):
        grid = arr[:, :, c].reshape(8, 28, 8, 28).mean(axis=(1, 3))
        features.extend(grid.flatten())
    
    # Edge detection approximation using gradients (2 directions × 64 = 128)
    gray = arr.mean(axis=2)
    gx = np.abs(np.diff(gray, axis=1)).mean(axis=0)
    gy = np.abs(np.diff(gray, axis=0)).mean(axis=1)
    # Resample to 64 values each
    features.extend(np.interp(np.linspace(0, len(gx)-1, 64), np.arange(len(gx)), gx))
    features.extend(np.interp(np.linspace(0, len(gy)-1, 64), np.arange(len(gy)), gy))
    
    # Pad or truncate to 1280 dimensions for compatibility
    features = np.array(features, dtype=np.float32)
    if len(features) < 1280:
        features = np.pad(features, (0, 1280 - len(features)), mode='constant')
    else:
        features = features[:1280]
    
    return features


def extract_image_features(filepath: str) -> np.ndarray:
    """
    Extract CNN features from a single image using pretrained EfficientNet-B0.
    Returns a 1-D float32 array of shape (1280,).
    Falls back to simple features if torch is not available.
    """
    try:
        import torch
        from torchvision import models, transforms
        import torch.nn as nn
    except ImportError:
        # Torch not available - use simple feature extraction
        return _extract_simple_features(filepath)

    global _CNN_MODEL, _CNN_TRANSFORM
    try:
        _CNN_MODEL  # already loaded
    except NameError:
        _CNN_MODEL = None
        _CNN_TRANSFORM = None

    if _CNN_MODEL is None:
        _cnn = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)
        _cnn.classifier = nn.Identity()

        # Load fine-tuned backbone weights if available (blocks 7-8 adapted)
        _ft_path = os.path.join(BASE_DIR, "finetuned_backbone.pth")
        if os.path.exists(_ft_path):
            _cnn.load_state_dict(torch.load(_ft_path, map_location="cpu"))

        _cnn.eval()
        for p in _cnn.parameters():
            p.requires_grad = False
        _CNN_MODEL = _cnn
        _CNN_TRANSFORM = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

    img = Image.open(filepath).convert("RGB")
    try:
        # Light test-time augmentation: original + horizontal flip.
        imgs = [img, img.transpose(Image.FLIP_LEFT_RIGHT)]
        tensors = torch.stack([_CNN_TRANSFORM(im) for im in imgs], dim=0)
        with torch.inference_mode():
            feats = _CNN_MODEL(tensors)
        # Average pooled features across views
        feats = feats.mean(dim=0)
        return feats.squeeze().cpu().numpy()
    finally:
        img.close()


def validate_medical_image(filepath: str) -> tuple[bool, str]:
    """Basic sanity checks on the uploaded image."""
    try:
        img = Image.open(filepath)
        w, h = img.size
        if w < 50 or h < 50:
            return False, "Image too small (min 50 × 50 px)."
        if w > 10_000 or h > 10_000:
            return False, "Image too large (max 10 000 × 10 000 px)."
        return True, "Valid image."
    except Exception as exc:
        return False, f"Cannot process image: {exc}"


def augment_image(img_array: np.ndarray) -> list[np.ndarray]:
    """Lightweight augmentations for a single (H, W, 3) array."""
    return [
        img_array,
        np.fliplr(img_array),
        np.clip(img_array * 1.2, 0, 1),
        np.clip(img_array * 0.8, 0, 1),
    ]


# ──────────────────────────────────────────────────────────────────────
# Result Formatting
# ──────────────────────────────────────────────────────────────────────

def format_prediction_result(disease: str, confidence: float, method: str = "symptom") -> dict:
    return {
        "disease": disease,
        "confidence": round(confidence, 2),
        "method": method,
        "severity": _severity_label(confidence),
        "description": get_disease_description(disease),
        "precautions": get_disease_precautions(disease),
    }


def _severity_label(confidence: float) -> str:
    if confidence >= 85:
        return "High confidence — consult a doctor"
    if confidence >= 65:
        return "Moderate confidence — monitoring recommended"
    return "Low confidence — more tests needed"


# ──────────────────────────────────────────────────────────────────────
# AI Cure Assistant — Disease Treatment Database
# ──────────────────────────────────────────────────────────────────────

DISEASE_CURE_DATABASE = {
    # ── Skin Diseases ──
    "Acne / Rosacea": {
        "cure_advice": [
            "Wash your face twice daily with a gentle cleanser",
            "Use non-comedogenic moisturizers and sunscreen",
            "Apply topical retinoids or benzoyl peroxide as directed",
            "Avoid touching your face and popping pimples",
            "Consider consulting a dermatologist for prescription treatments"
        ],
        "products": [
            {"name": "CeraVe Acne Foaming Cream Cleanser", "url": "https://www.amazon.com/dp/B08GWVLKK1", "type": "Cleanser"},
            {"name": "La Roche-Posay Effaclar Duo", "url": "https://www.amazon.com/dp/B00HNSSV3M", "type": "Treatment"},
            {"name": "Differin Adapalene Gel 0.1%", "url": "https://www.amazon.com/dp/B07L1PHSY9", "type": "Retinoid"},
            {"name": "Paula's Choice 2% BHA Liquid Exfoliant", "url": "https://www.amazon.com/dp/B00949CTQQ", "type": "Exfoliant"}
        ],
        "when_to_see_doctor": "If acne is severe, painful, or leaving scars"
    },
    "Eczema": {
        "cure_advice": [
            "Keep skin well moisturized with fragrance-free creams",
            "Avoid known triggers like harsh soaps and allergens",
            "Take lukewarm (not hot) showers and pat dry gently",
            "Wear soft, breathable fabrics like cotton",
            "Apply prescribed corticosteroid creams during flare-ups"
        ],
        "products": [
            {"name": "Eucerin Eczema Relief Cream", "url": "https://www.amazon.com/dp/B003BMJGKE", "type": "Moisturizer"},
            {"name": "Aveeno Eczema Therapy Daily Moisturizing Cream", "url": "https://www.amazon.com/dp/B003O7IBZC", "type": "Moisturizer"},
            {"name": "CeraVe Moisturizing Cream", "url": "https://www.amazon.com/dp/B00TTD9BRC", "type": "Moisturizer"},
            {"name": "Vanicream Moisturizing Skin Cream", "url": "https://www.amazon.com/dp/B000NWGCZ2", "type": "Sensitive Skin"}
        ],
        "when_to_see_doctor": "If eczema spreads, becomes infected, or disrupts sleep"
    },
    "Psoriasis / Lichen Planus": {
        "cure_advice": [
            "Use medicated shampoos containing coal tar or salicylic acid",
            "Apply topical corticosteroids to reduce inflammation",
            "Keep skin moisturized to prevent cracking",
            "Get moderate sunlight exposure (with doctor's approval)",
            "Manage stress through relaxation techniques"
        ],
        "products": [
            {"name": "MG217 Psoriasis Cream", "url": "https://www.amazon.com/dp/B001G7QVGS", "type": "Treatment"},
            {"name": "Dermarest Psoriasis Medicated Shampoo", "url": "https://www.amazon.com/dp/B00KGAZL3G", "type": "Shampoo"},
            {"name": "Gold Bond Multi-Symptom Psoriasis Relief", "url": "https://www.amazon.com/dp/B007OXK15M", "type": "Cream"},
            {"name": "Psoriasin Deep Moisturizing Ointment", "url": "https://www.amazon.com/dp/B005EH4TLI", "type": "Ointment"}
        ],
        "when_to_see_doctor": "If plaques cover large areas or joint pain develops"
    },
    "Contact Dermatitis": {
        "cure_advice": [
            "Identify and avoid the irritant or allergen causing the reaction",
            "Wash affected area immediately after exposure",
            "Apply cool, wet compresses to soothe itching",
            "Use over-the-counter hydrocortisone cream",
            "Take oral antihistamines for severe itching"
        ],
        "products": [
            {"name": "Cortizone-10 Maximum Strength", "url": "https://www.amazon.com/dp/B001F51A0M", "type": "Anti-itch"},
            {"name": "Benadryl Anti-Itch Cream", "url": "https://www.amazon.com/dp/B06XS3SB7J", "type": "Antihistamine"},
            {"name": "Aquaphor Healing Ointment", "url": "https://www.amazon.com/dp/B0107QPFBU", "type": "Healing"},
            {"name": "Aveeno Anti-Itch Concentrated Lotion", "url": "https://www.amazon.com/dp/B001F0RA0G", "type": "Lotion"}
        ],
        "when_to_see_doctor": "If rash is severe, blistering, or on face/genitals"
    },
    "Fungal Infection": {
        "cure_advice": [
            "Keep affected area clean and dry",
            "Apply antifungal cream, powder, or spray",
            "Wear loose-fitting, breathable clothing",
            "Change socks and underwear daily",
            "Avoid sharing personal items like towels"
        ],
        "products": [
            {"name": "Lotrimin AF Antifungal Cream", "url": "https://www.amazon.com/dp/B00B2A1P3E", "type": "Antifungal"},
            {"name": "Lamisil AT Cream", "url": "https://www.amazon.com/dp/B00K2XT0NQ", "type": "Antifungal"},
            {"name": "Tinactin Antifungal Powder Spray", "url": "https://www.amazon.com/dp/B00L73Y1R0", "type": "Spray"},
            {"name": "Desenex Antifungal Powder", "url": "https://www.amazon.com/dp/B000052XUT", "type": "Powder"}
        ],
        "when_to_see_doctor": "If infection spreads, doesn't improve in 2 weeks, or affects nails"
    },
    "Tinea / Ringworm / Candidiasis": {
        "cure_advice": [
            "Apply over-the-counter antifungal cream twice daily",
            "Keep the infected area clean and dry",
            "Wash bedding and clothes in hot water",
            "Avoid scratching to prevent spreading",
            "Continue treatment for 1-2 weeks after symptoms clear"
        ],
        "products": [
            {"name": "Lotrimin Ultra Antifungal Cream", "url": "https://www.amazon.com/dp/B09MKH32QR", "type": "Antifungal"},
            {"name": "Monistat Care Chafing Relief Powder Gel", "url": "https://www.amazon.com/dp/B000FKLKXQ", "type": "Prevention"},
            {"name": "Clotrimazole Antifungal Cream 1%", "url": "https://www.amazon.com/dp/B01JA3PCAQ", "type": "Generic"},
            {"name": "Miconazole Nitrate 2% Antifungal Cream", "url": "https://www.amazon.com/dp/B07DVVZWGG", "type": "Antifungal"}
        ],
        "when_to_see_doctor": "If ringworm is on scalp, face, or doesn't respond to OTC treatment"
    },
    "Nail Fungus": {
        "cure_advice": [
            "Keep nails trimmed short and filed smooth",
            "Apply antifungal nail lacquer as directed",
            "Wear moisture-wicking socks",
            "Disinfect nail clippers after each use",
            "Wear protective footwear in public showers"
        ],
        "products": [
            {"name": "Kerasal Fungal Nail Renewal", "url": "https://www.amazon.com/dp/B007RTH5G8", "type": "Treatment"},
            {"name": "Fungi-Nail Anti-Fungal Solution", "url": "https://www.amazon.com/dp/B000QTHM1M", "type": "Solution"},
            {"name": "Emoninail Nail Fungal Treatment", "url": "https://www.amazon.com/dp/B07JNPKPGL", "type": "Treatment"},
            {"name": "Tea Tree Oil 100% Pure", "url": "https://www.amazon.com/dp/B07L9BGML2", "type": "Natural"}
        ],
        "when_to_see_doctor": "If nail becomes painful, thickens significantly, or separates from nail bed"
    },
    "Urticaria": {
        "cure_advice": [
            "Take oral antihistamines to relieve itching",
            "Apply cool compresses to affected areas",
            "Avoid known triggers (foods, medications, stress)",
            "Wear loose, comfortable clothing",
            "Keep a diary to identify potential triggers"
        ],
        "products": [
            {"name": "Zyrtec 24 Hour Allergy Relief", "url": "https://www.amazon.com/dp/B074G2BKFG", "type": "Antihistamine"},
            {"name": "Allegra 24 Hour Allergy Relief", "url": "https://www.amazon.com/dp/B08DHQSG6G", "type": "Antihistamine"},
            {"name": "Claritin 24 Hour Allergy Relief", "url": "https://www.amazon.com/dp/B08DP92YC5", "type": "Antihistamine"},
            {"name": "Benadryl Ultratabs", "url": "https://www.amazon.com/dp/B0000AA2O1", "type": "Fast Acting"}
        ],
        "when_to_see_doctor": "If hives last more than 6 weeks or accompanied by swelling/breathing difficulty"
    },
    "Scabies / Lyme Disease": {
        "cure_advice": [
            "For scabies: Apply prescription permethrin cream as directed",
            "Wash all bedding, clothing, and towels in hot water",
            "Vacuum floors and furniture thoroughly",
            "Treat all household members simultaneously",
            "For Lyme: Start antibiotics immediately if tick bite suspected"
        ],
        "products": [
            {"name": "Nix Permethrin Lice Treatment", "url": "https://www.amazon.com/dp/B000GCSCGE", "type": "Treatment"},
            {"name": "Sulfur Soap for Scabies", "url": "https://www.amazon.com/dp/B00D9RGLNO", "type": "Soap"},
            {"name": "Bug Bite Thing Suction Tool", "url": "https://www.amazon.com/dp/B07B6MD7MM", "type": "Tool"},
            {"name": "After Bite Itch Eraser", "url": "https://www.amazon.com/dp/B000P97DCE", "type": "Relief"}
        ],
        "when_to_see_doctor": "Immediately - both conditions require medical evaluation"
    },
    "Warts / Molluscum": {
        "cure_advice": [
            "Apply over-the-counter salicylic acid treatment daily",
            "Cover warts with duct tape or bandages to prevent spreading",
            "Avoid picking or scratching warts",
            "Do not share personal items",
            "Boost immune system with proper nutrition and rest"
        ],
        "products": [
            {"name": "Compound W Wart Remover", "url": "https://www.amazon.com/dp/B00OICGM10", "type": "Treatment"},
            {"name": "Dr. Scholl's Freeze Away Wart Remover", "url": "https://www.amazon.com/dp/B000GCPXKM", "type": "Freeze"},
            {"name": "ZymaDerm for Molluscum", "url": "https://www.amazon.com/dp/B00186CTMU", "type": "Natural"},
            {"name": "Wartner Wart Removal System", "url": "https://www.amazon.com/dp/B000VZV5UE", "type": "Treatment"}
        ],
        "when_to_see_doctor": "If warts spread rapidly, appear on face/genitals, or are painful"
    },
    # ── Eye Diseases ──
    "Cataract": {
        "cure_advice": [
            "Surgery is the only effective treatment for cataracts",
            "Use brighter lights for reading and activities",
            "Wear anti-glare sunglasses outdoors",
            "Update eyeglass prescription regularly",
            "Protect eyes from UV exposure"
        ],
        "products": [
            {"name": "Can-C Eye Drops", "url": "https://www.amazon.com/dp/B00166FTVU", "type": "Supplement"},
            {"name": "TheraTears Eye Drops", "url": "https://www.amazon.com/dp/B00CKEZ586", "type": "Lubricant"},
            {"name": "Polarized Anti-Glare Sunglasses", "url": "https://www.amazon.com/dp/B07L4K9LQM", "type": "Protection"},
            {"name": "AREDS 2 Eye Vitamins", "url": "https://www.amazon.com/dp/B07ZX1L1K3", "type": "Supplement"}
        ],
        "when_to_see_doctor": "When vision impairment affects daily activities"
    },
    "Glaucoma": {
        "cure_advice": [
            "Use prescribed eye drops exactly as directed",
            "Never skip doses of glaucoma medication",
            "Get regular eye pressure checks",
            "Avoid activities that increase eye pressure",
            "Protect eyes from injury"
        ],
        "products": [
            {"name": "Systane Ultra Lubricant Eye Drops", "url": "https://www.amazon.com/dp/B001F0R8C2", "type": "Lubricant"},
            {"name": "Refresh Optive Lubricant Eye Drops", "url": "https://www.amazon.com/dp/B003XN42L0", "type": "Lubricant"},
            {"name": "Eye Pressure Monitor (Tonometer)", "url": "https://www.amazon.com/dp/B07C3H4K7T", "type": "Monitor"},
            {"name": "AREDS 2 Eye Health Formula", "url": "https://www.amazon.com/dp/B07D34XXVY", "type": "Supplement"}
        ],
        "when_to_see_doctor": "Regular checkups required - follow ophthalmologist schedule"
    },
    "Diabetic Retinopathy": {
        "cure_advice": [
            "Control blood sugar levels strictly",
            "Maintain healthy blood pressure and cholesterol",
            "Get comprehensive dilated eye exams annually",
            "Stop smoking immediately",
            "Follow diabetic diet and exercise plan"
        ],
        "products": [
            {"name": "Blood Glucose Monitor Kit", "url": "https://www.amazon.com/dp/B08LX4R3W5", "type": "Monitor"},
            {"name": "Diabetic Eye Health Vitamins", "url": "https://www.amazon.com/dp/B08D993LN1", "type": "Supplement"},
            {"name": "Low Sugar Cookbook for Diabetics", "url": "https://www.amazon.com/dp/B08F9LFTNY", "type": "Guide"},
            {"name": "TheraTears Nutrition Omega-3", "url": "https://www.amazon.com/dp/B002RL8FCU", "type": "Supplement"}
        ],
        "when_to_see_doctor": "Immediately if vision changes, floaters, or dark spots appear"
    },
    "Healthy Eye": {
        "cure_advice": [
            "Continue regular eye checkups every 1-2 years",
            "Protect eyes from UV light with sunglasses",
            "Follow 20-20-20 rule for screen use",
            "Maintain a diet rich in omega-3 and vitamins A, C, E",
            "Stay hydrated and get adequate sleep"
        ],
        "products": [
            {"name": "Blue Light Blocking Glasses", "url": "https://www.amazon.com/dp/B082F9JYHZ", "type": "Protection"},
            {"name": "Ocuvite Eye Vitamin & Mineral Supplement", "url": "https://www.amazon.com/dp/B00V5KR0DG", "type": "Supplement"},
            {"name": "Rohto Eye Drops Cooling Relief", "url": "https://www.amazon.com/dp/B001F0DGRI", "type": "Refreshing"},
            {"name": "Eye Mask for Sleep", "url": "https://www.amazon.com/dp/B07PRK1QS7", "type": "Rest"}
        ],
        "when_to_see_doctor": "Regular annual checkups recommended"
    },
    # ── Common Diseases from Symptom Prediction ──
    "Common Cold": {
        "cure_advice": [
            "Rest and stay hydrated with water, juice, and warm soups",
            "Use saline nasal spray to relieve congestion",
            "Take over-the-counter cold medications for symptom relief",
            "Gargle with warm salt water for sore throat",
            "Use a humidifier to add moisture to the air"
        ],
        "products": [
            {"name": "Vicks DayQuil/NyQuil Combo Pack", "url": "https://www.amazon.com/dp/B00N1JXF9G", "type": "Cold Relief"},
            {"name": "Mucinex Fast-Max Cold & Flu", "url": "https://www.amazon.com/dp/B00G3WOSYA", "type": "Multi-Symptom"},
            {"name": "Zicam Cold Remedy Nasal Swabs", "url": "https://www.amazon.com/dp/B001GCU4ZW", "type": "Shortening"},
            {"name": "Vicks Warm Mist Humidifier", "url": "https://www.amazon.com/dp/B001FWXKTA", "type": "Humidifier"}
        ],
        "when_to_see_doctor": "If symptoms last more than 10 days or worsen"
    },
    "Allergy": {
        "cure_advice": [
            "Identify and avoid allergen triggers",
            "Take antihistamines regularly during allergy season",
            "Use air purifiers with HEPA filters indoors",
            "Keep windows closed during high pollen days",
            "Shower after outdoor activities to remove allergens"
        ],
        "products": [
            {"name": "Zyrtec 24 Hour Allergy Relief", "url": "https://www.amazon.com/dp/B074G2BKFG", "type": "Antihistamine"},
            {"name": "Flonase Allergy Relief Nasal Spray", "url": "https://www.amazon.com/dp/B00TXNZ3K8", "type": "Nasal Spray"},
            {"name": "LEVOIT Air Purifier with HEPA Filter", "url": "https://www.amazon.com/dp/B07VVK39F7", "type": "Air Purifier"},
            {"name": "Nasacort Allergy 24HR Spray", "url": "https://www.amazon.com/dp/B00KMLS9XK", "type": "Nasal Spray"}
        ],
        "when_to_see_doctor": "If allergies cause breathing difficulties or don't respond to OTC medications"
    },
    "Viral Fever": {
        "cure_advice": [
            "Rest and avoid strenuous activities",
            "Stay well hydrated with fluids",
            "Take fever reducers like acetaminophen or ibuprofen",
            "Use cool compresses on forehead if fever is high",
            "Isolate to prevent spreading to others"
        ],
        "products": [
            {"name": "Tylenol Extra Strength", "url": "https://www.amazon.com/dp/B0BJYBS15M", "type": "Pain/Fever"},
            {"name": "Advil Dual Action", "url": "https://www.amazon.com/dp/B08P3YJD5L", "type": "Pain/Fever"},
            {"name": "Digital Thermometer", "url": "https://www.amazon.com/dp/B07YK7SDQR", "type": "Monitor"},
            {"name": "Pedialyte Electrolyte Solution", "url": "https://www.amazon.com/dp/B0741G3CBF", "type": "Hydration"}
        ],
        "when_to_see_doctor": "If fever exceeds 103°F (39.4°C) or lasts more than 3 days"
    },
    "Pneumonia": {
        "cure_advice": [
            "Seek medical attention for proper diagnosis and antibiotics",
            "Complete the full course of prescribed antibiotics",
            "Rest as much as possible",
            "Stay well hydrated",
            "Use a humidifier to ease breathing"
        ],
        "products": [
            {"name": "Pulse Oximeter", "url": "https://www.amazon.com/dp/B07PQ8WTC4", "type": "Monitor"},
            {"name": "Honeywell Cool Mist Humidifier", "url": "https://www.amazon.com/dp/B00KXEEXZ0", "type": "Humidifier"},
            {"name": "Robitussin Maximum Strength", "url": "https://www.amazon.com/dp/B07L5GPYZ8", "type": "Cough"},
            {"name": "Vicks VapoRub", "url": "https://www.amazon.com/dp/B07B3PF72Y", "type": "Chest Rub"}
        ],
        "when_to_see_doctor": "Immediately - pneumonia requires medical treatment"
    },
    "Malaria": {
        "cure_advice": [
            "Seek immediate medical treatment - antimalarial drugs required",
            "Complete the full course of medication",
            "Rest and stay hydrated",
            "Use fever-reducing medications as needed",
            "Use mosquito nets to prevent re-infection"
        ],
        "products": [
            {"name": "Mosquito Net Bed Canopy", "url": "https://www.amazon.com/dp/B07N2C3GNK", "type": "Prevention"},
            {"name": "DEET Insect Repellent", "url": "https://www.amazon.com/dp/B000PGE3VW", "type": "Repellent"},
            {"name": "Picaridin Insect Repellent", "url": "https://www.amazon.com/dp/B01LZOW8MH", "type": "Repellent"},
            {"name": "Electrolyte Powder Packets", "url": "https://www.amazon.com/dp/B01MXDAHBR", "type": "Hydration"}
        ],
        "when_to_see_doctor": "Immediately - malaria is a medical emergency"
    },
    "Migraine": {
        "cure_advice": [
            "Rest in a dark, quiet room",
            "Apply cold or warm compresses to head and neck",
            "Take pain relievers at first sign of migraine",
            "Stay hydrated and maintain regular sleep schedule",
            "Identify and avoid personal migraine triggers"
        ],
        "products": [
            {"name": "Excedrin Migraine", "url": "https://www.amazon.com/dp/B001GAOAME", "type": "Pain Relief"},
            {"name": "TheraICE Migraine Relief Cap", "url": "https://www.amazon.com/dp/B07FZLMCQJ", "type": "Cold Therapy"},
            {"name": "Migraine Glasses FL-41 Tint", "url": "https://www.amazon.com/dp/B08F3YVMYL", "type": "Light Filter"},
            {"name": "Peppermint Essential Oil Roll-On", "url": "https://www.amazon.com/dp/B07VQP9F8P", "type": "Aromatherapy"}
        ],
        "when_to_see_doctor": "If migraines are severe, frequent, or change in pattern"
    },
    "Arthritis": {
        "cure_advice": [
            "Stay active with low-impact exercises",
            "Apply hot or cold therapy to affected joints",
            "Maintain a healthy weight to reduce joint stress",
            "Take anti-inflammatory medications as directed",
            "Consider physical therapy for exercise guidance"
        ],
        "products": [
            {"name": "Voltaren Arthritis Pain Gel", "url": "https://www.amazon.com/dp/B0847HQNL2", "type": "Topical"},
            {"name": "Compression Gloves for Arthritis", "url": "https://www.amazon.com/dp/B07GXBV4BJ", "type": "Support"},
            {"name": "Paraffin Wax Bath for Hands", "url": "https://www.amazon.com/dp/B00164YIDS", "type": "Heat Therapy"},
            {"name": "Move Free Advanced Joint Supplement", "url": "https://www.amazon.com/dp/B007J6HKZQ", "type": "Supplement"}
        ],
        "when_to_see_doctor": "If joint pain is severe, persistent, or causes limited mobility"
    },
    "Gastroenteritis": {
        "cure_advice": [
            "Stay hydrated with clear fluids and electrolyte solutions",
            "Follow the BRAT diet (bananas, rice, applesauce, toast)",
            "Avoid dairy, caffeine, and fatty foods temporarily",
            "Rest and let your digestive system recover",
            "Wash hands frequently to prevent spreading"
        ],
        "products": [
            {"name": "Pedialyte Electrolyte Solution", "url": "https://www.amazon.com/dp/B0741G3CBF", "type": "Hydration"},
            {"name": "Imodium Anti-Diarrheal", "url": "https://www.amazon.com/dp/B00HGP8GJG", "type": "Anti-Diarrheal"},
            {"name": "Pepto-Bismol", "url": "https://www.amazon.com/dp/B0009EYXPK", "type": "Stomach Relief"},
            {"name": "Culturelle Digestive Probiotics", "url": "https://www.amazon.com/dp/B00ULGCDFE", "type": "Probiotics"}
        ],
        "when_to_see_doctor": "If dehydration occurs, blood in stool, or symptoms last more than 3 days"
    },
    "Tuberculosis": {
        "cure_advice": [
            "Take all prescribed medications for the full duration (6-9 months)",
            "Never skip doses to prevent drug resistance",
            "Cover mouth when coughing and dispose of tissues properly",
            "Ensure good ventilation in living spaces",
            "Get adequate rest and nutrition"
        ],
        "products": [
            {"name": "N95 Respirator Masks", "url": "https://www.amazon.com/dp/B08YS6WJZ3", "type": "Protection"},
            {"name": "HEPA Air Purifier", "url": "https://www.amazon.com/dp/B07VVK39F7", "type": "Air Quality"},
            {"name": "Pill Organizer Weekly", "url": "https://www.amazon.com/dp/B07P7BLRQ8", "type": "Medication"},
            {"name": "Immune Support Vitamins", "url": "https://www.amazon.com/dp/B00EZQM0TK", "type": "Supplement"}
        ],
        "when_to_see_doctor": "TB requires continuous medical supervision"
    },
    "Bronchitis": {
        "cure_advice": [
            "Rest and drink plenty of fluids",
            "Use a humidifier to moisten the air",
            "Take over-the-counter cough suppressants at night",
            "Avoid smoking and secondhand smoke",
            "Use honey to soothe throat (adults only)"
        ],
        "products": [
            {"name": "Delsym 12-Hour Cough Relief", "url": "https://www.amazon.com/dp/B001PYQC2W", "type": "Cough Suppressant"},
            {"name": "Mucinex Expectorant", "url": "https://www.amazon.com/dp/B001EOPVTS", "type": "Expectorant"},
            {"name": "Pure Enrichment MistAire Humidifier", "url": "https://www.amazon.com/dp/B013IJPTFK", "type": "Humidifier"},
            {"name": "Manuka Honey", "url": "https://www.amazon.com/dp/B07B5QJPCS", "type": "Natural Remedy"}
        ],
        "when_to_see_doctor": "If cough lasts more than 3 weeks, produces blood, or causes difficulty breathing"
    },
    # ── Additional skin conditions ──
    "Atopic Dermatitis": {
        "cure_advice": [
            "Moisturize skin frequently with thick, fragrance-free creams",
            "Take short, lukewarm baths and moisturize immediately after",
            "Identify and avoid personal triggers",
            "Wear soft fabrics like cotton",
            "Use prescribed medications during flare-ups"
        ],
        "products": [
            {"name": "CeraVe Moisturizing Cream", "url": "https://www.amazon.com/dp/B00TTD9BRC", "type": "Moisturizer"},
            {"name": "Eucerin Eczema Relief Cream", "url": "https://www.amazon.com/dp/B003BMJGKE", "type": "Treatment"},
            {"name": "La Roche-Posay Lipikar Balm", "url": "https://www.amazon.com/dp/B002BYNXYC", "type": "Balm"},
            {"name": "Cortizone-10 Eczema Relief", "url": "https://www.amazon.com/dp/B0062KJC12", "type": "Anti-itch"}
        ],
        "when_to_see_doctor": "If skin becomes infected or doesn't respond to treatment"
    },
    "Melanoma (suspected)": {
        "cure_advice": [
            "Do NOT delay - seek immediate medical evaluation",
            "Do not attempt to remove or treat the lesion yourself",
            "Document the appearance with photos for comparison",
            "Protect the area from sun exposure",
            "Prepare questions for your dermatologist appointment"
        ],
        "products": [
            {"name": "EltaMD UV Clear Sunscreen SPF 46", "url": "https://www.amazon.com/dp/B002MSN3QQ", "type": "Sun Protection"},
            {"name": "La Roche-Posay Anthelios Sunscreen SPF 60", "url": "https://www.amazon.com/dp/B002CML1VG", "type": "Sun Protection"},
            {"name": "Skin Check Body Map Journal", "url": "https://www.amazon.com/dp/B07T8N7KQJ", "type": "Tracking"},
            {"name": "UV Protection Clothing", "url": "https://www.amazon.com/dp/B07JLHD6KM", "type": "Clothing"}
        ],
        "when_to_see_doctor": "IMMEDIATELY - melanoma requires urgent medical attention"
    },
    "Lupus": {
        "cure_advice": [
            "Follow your treatment plan strictly",
            "Protect skin from sun exposure",
            "Get adequate rest and manage stress",
            "Maintain regular exercise within your limits",
            "Keep all medical appointments"
        ],
        "products": [
            {"name": "Neutrogena Ultra Sheer SPF 100+", "url": "https://www.amazon.com/dp/B06XSTPPKX", "type": "Sunscreen"},
            {"name": "UPF 50+ Sun Protection Hat", "url": "https://www.amazon.com/dp/B01KGTEZ4I", "type": "Sun Protection"},
            {"name": "Anti-Inflammatory Supplement", "url": "https://www.amazon.com/dp/B000GFSVS2", "type": "Supplement"},
            {"name": "Vitamin D3 Supplement", "url": "https://www.amazon.com/dp/B00LU2CD4A", "type": "Vitamin"}
        ],
        "when_to_see_doctor": "Regular checkups required - follow rheumatologist schedule"
    },
    "Herpes / HPV": {
        "cure_advice": [
            "Take antiviral medications as prescribed",
            "Keep affected areas clean and dry",
            "Avoid intimate contact during outbreaks",
            "Manage stress to reduce outbreak frequency",
            "Inform partners about the condition"
        ],
        "products": [
            {"name": "Abreva Cold Sore Treatment", "url": "https://www.amazon.com/dp/B000GG1R94", "type": "Treatment"},
            {"name": "Lysine Supplement", "url": "https://www.amazon.com/dp/B002HL86Q6", "type": "Supplement"},
            {"name": "Tea Tree Oil for Skin", "url": "https://www.amazon.com/dp/B07L9BGML2", "type": "Natural"},
            {"name": "Zinc Oxide Cream", "url": "https://www.amazon.com/dp/B00IXNB26G", "type": "Protective"}
        ],
        "when_to_see_doctor": "For initial diagnosis, frequent outbreaks, or if symptoms worsen"
    },
    "Cellulitis / Impetigo": {
        "cure_advice": [
            "Take prescribed antibiotics exactly as directed",
            "Keep affected area clean and covered",
            "Elevate affected limb if possible",
            "Apply warm compresses to reduce discomfort",
            "Watch for signs of spreading infection"
        ],
        "products": [
            {"name": "Bacitracin Antibiotic Ointment", "url": "https://www.amazon.com/dp/B000GCMHZQ", "type": "Topical"},
            {"name": "Hibiclens Antiseptic Skin Cleanser", "url": "https://www.amazon.com/dp/B00CYXN86C", "type": "Cleanser"},
            {"name": "Non-Stick Sterile Gauze Pads", "url": "https://www.amazon.com/dp/B0084HHHXW", "type": "Bandage"},
            {"name": "Medical Tape Sensitive Skin", "url": "https://www.amazon.com/dp/B08L97BVWX", "type": "Tape"}
        ],
        "when_to_see_doctor": "If redness spreads, fever develops, or symptoms worsen"
    },
    "Alopecia": {
        "cure_advice": [
            "Minimize stress through relaxation techniques",
            "Eat a balanced diet rich in protein and iron",
            "Avoid harsh hair treatments and tight hairstyles",
            "Consider minoxidil or other FDA-approved treatments",
            "Be gentle when washing and styling hair"
        ],
        "products": [
            {"name": "Rogaine (Minoxidil) 5% Foam", "url": "https://www.amazon.com/dp/B0012BNVE8", "type": "Treatment"},
            {"name": "Biotin Hair Growth Supplement", "url": "https://www.amazon.com/dp/B01E9HX612", "type": "Supplement"},
            {"name": "Nioxin Scalp Treatment System", "url": "https://www.amazon.com/dp/B002GHO1M8", "type": "System"},
            {"name": "Keratin Hair Building Fibers", "url": "https://www.amazon.com/dp/B019HZ9N0A", "type": "Cosmetic"}
        ],
        "when_to_see_doctor": "If hair loss is sudden, patchy, or accompanied by other symptoms"
    },
    "Seborrheic Keratosis": {
        "cure_advice": [
            "These growths are benign and often don't require treatment",
            "Avoid picking or scratching the growths",
            "Protect skin from sun damage",
            "Monitor for any changes in appearance",
            "Consider removal for cosmetic reasons or if irritated"
        ],
        "products": [
            {"name": "CeraVe SA Smoothing Cream", "url": "https://www.amazon.com/dp/B07ZJP2MMZ", "type": "Exfoliant"},
            {"name": "AmLactin Daily Moisturizing Lotion", "url": "https://www.amazon.com/dp/B00168G4YM", "type": "Exfoliant"},
            {"name": "SPF 50 Sunscreen", "url": "https://www.amazon.com/dp/B002CML1VG", "type": "Protection"},
            {"name": "Skin Tag Remover Patches", "url": "https://www.amazon.com/dp/B07KHZ99YK", "type": "Removal"}
        ],
        "when_to_see_doctor": "If growth changes color, bleeds, or becomes painful"
    },
    "Dermatofibroma": {
        "cure_advice": [
            "Dermatofibromas are benign and typically don't need treatment",
            "Leave them alone unless they cause discomfort",
            "Protect the area from injury",
            "Monitor for any changes in size or color",
            "Surgical removal is optional for cosmetic concerns"
        ],
        "products": [
            {"name": "Scar Treatment Silicone Sheets", "url": "https://www.amazon.com/dp/B00D8NWKKS", "type": "Scar Care"},
            {"name": "Mederma Scar Cream", "url": "https://www.amazon.com/dp/B000RREAZ0", "type": "Treatment"},
            {"name": "Vitamin E Oil", "url": "https://www.amazon.com/dp/B06Y69XGCW", "type": "Skin Care"},
            {"name": "Bandage Covers for Protection", "url": "https://www.amazon.com/dp/B001EP6OXQ", "type": "Protection"}
        ],
        "when_to_see_doctor": "If appearance changes, growth accelerates, or becomes painful"
    },
    "Vasculitis": {
        "cure_advice": [
            "Follow prescribed treatment plan strictly",
            "Take immunosuppressive medications as directed",
            "Report any new symptoms promptly",
            "Protect skin from injury",
            "Maintain a healthy lifestyle"
        ],
        "products": [
            {"name": "Compression Stockings", "url": "https://www.amazon.com/dp/B07CMM4HL5", "type": "Support"},
            {"name": "Anti-Inflammatory Turmeric Supplement", "url": "https://www.amazon.com/dp/B00WT4D57K", "type": "Supplement"},
            {"name": "Omega-3 Fish Oil", "url": "https://www.amazon.com/dp/B016YZUEWG", "type": "Anti-inflammatory"},
            {"name": "Gentle Skin Cleanser", "url": "https://www.amazon.com/dp/B01N7T7Y9E", "type": "Cleanser"}
        ],
        "when_to_see_doctor": "Regular monitoring required - follow specialist's schedule"
    },
    "Vascular Tumor": {
        "cure_advice": [
            "Most benign vascular tumors don't require treatment",
            "Monitor for changes in size or appearance",
            "Protect the area from trauma",
            "Avoid blood thinners if possible",
            "Discuss treatment options with your doctor"
        ],
        "products": [
            {"name": "Protective Bandages", "url": "https://www.amazon.com/dp/B001EP6OXQ", "type": "Protection"},
            {"name": "Arnica Gel for Bruising", "url": "https://www.amazon.com/dp/B00016QQJY", "type": "Healing"},
            {"name": "Silicone Scar Sheets", "url": "https://www.amazon.com/dp/B00D4FSHHW", "type": "Post-treatment"},
            {"name": "Vitamin K Cream", "url": "https://www.amazon.com/dp/B00BVHZD4O", "type": "Skin Health"}
        ],
        "when_to_see_doctor": "If tumor grows rapidly, bleeds, or causes pain"
    },
    "Bullous Disease": {
        "cure_advice": [
            "Do not pop or drain blisters yourself",
            "Keep affected areas clean and protected",
            "Follow prescribed treatment plan",
            "Wear soft, loose clothing",
            "Maintain good nutrition for healing"
        ],
        "products": [
            {"name": "Non-Stick Wound Pads", "url": "https://www.amazon.com/dp/B0084HHHXW", "type": "Bandage"},
            {"name": "Wound Healing Hydrogel", "url": "https://www.amazon.com/dp/B0009EILXI", "type": "Healing"},
            {"name": "Medical Tape for Sensitive Skin", "url": "https://www.amazon.com/dp/B08L97BVWX", "type": "Tape"},
            {"name": "Protein Supplement for Healing", "url": "https://www.amazon.com/dp/B00EMXK95E", "type": "Nutrition"}
        ],
        "when_to_see_doctor": "Immediately - bullous diseases require medical evaluation"
    },
    "Systemic Disease": {
        "cure_advice": [
            "Follow your healthcare team's treatment plan",
            "Take all medications as prescribed",
            "Monitor and report any new symptoms",
            "Maintain regular medical appointments",
            "Focus on overall health and wellness"
        ],
        "products": [
            {"name": "Pill Organizer with Alarm", "url": "https://www.amazon.com/dp/B07XV4WHVJ", "type": "Medication"},
            {"name": "Health Tracking Journal", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Tracking"},
            {"name": "Blood Pressure Monitor", "url": "https://www.amazon.com/dp/B08DGT3VSZ", "type": "Monitor"},
            {"name": "Multivitamin Supplement", "url": "https://www.amazon.com/dp/B00LUKBYI2", "type": "Supplement"}
        ],
        "when_to_see_doctor": "Follow prescribed monitoring schedule"
    },
    "Actinic Keratosis / Basal Cell Carcinoma": {
        "cure_advice": [
            "Seek immediate dermatological evaluation",
            "Protect skin from further sun damage",
            "Do not attempt self-treatment",
            "Follow up regularly after treatment",
            "Perform monthly skin self-exams"
        ],
        "products": [
            {"name": "EltaMD UV Clear SPF 46", "url": "https://www.amazon.com/dp/B002MSN3QQ", "type": "Sunscreen"},
            {"name": "UPF 50+ Sun Protection Clothing", "url": "https://www.amazon.com/dp/B07JLHD6KM", "type": "Protective"},
            {"name": "Wide Brim Sun Hat", "url": "https://www.amazon.com/dp/B01KGTEZ4I", "type": "Protection"},
            {"name": "Vitamin D Supplement", "url": "https://www.amazon.com/dp/B00LU2CD4A", "type": "Supplement"}
        ],
        "when_to_see_doctor": "IMMEDIATELY - precancerous/cancerous lesions require medical treatment"
    },
    "Exanthem / Drug Eruption": {
        "cure_advice": [
            "Stop taking the suspected medication (consult doctor first)",
            "Take antihistamines to relieve itching",
            "Apply cool compresses to affected areas",
            "Avoid hot showers and harsh soaps",
            "Document symptoms and medications for your doctor"
        ],
        "products": [
            {"name": "Benadryl Antihistamine", "url": "https://www.amazon.com/dp/B0000AA2O1", "type": "Antihistamine"},
            {"name": "Calamine Lotion", "url": "https://www.amazon.com/dp/B000GCVIY6", "type": "Soothing"},
            {"name": "Oatmeal Bath Treatment", "url": "https://www.amazon.com/dp/B0009XNJHM", "type": "Bath"},
            {"name": "Medication Allergy Alert Bracelet", "url": "https://www.amazon.com/dp/B07G3DKTZ4", "type": "Alert"}
        ],
        "when_to_see_doctor": "If accompanied by fever, difficulty breathing, or spreading rapidly"
    },
    "Vitiligo / Pigmentation Disorder": {
        "cure_advice": [
            "Protect depigmented skin from sun exposure",
            "Consider phototherapy treatment options",
            "Use cosmetic camouflage if desired",
            "Join support groups for emotional support",
            "Maintain overall skin health"
        ],
        "products": [
            {"name": "Dermablend Cover Creme", "url": "https://www.amazon.com/dp/B001EKTM2Q", "type": "Cosmetic"},
            {"name": "CoverBlend Concealer", "url": "https://www.amazon.com/dp/B001WUQG6G", "type": "Cosmetic"},
            {"name": "La Roche-Posay Anthelios SPF 60", "url": "https://www.amazon.com/dp/B002CML1VG", "type": "Sunscreen"},
            {"name": "Vitamin B12 Supplement", "url": "https://www.amazon.com/dp/B007K6XKT4", "type": "Supplement"}
        ],
        "when_to_see_doctor": "For treatment options and monitoring progression"
    },
    # ══════════════════════════════════════════════════════════════════════
    # Dataset-Specific Disease Entries (exact matches for symptom prediction)
    # ══════════════════════════════════════════════════════════════════════
    "(vertigo) Paroymsal  Positional Vertigo": {
        "cure_advice": [
            "Perform Epley maneuver or Brandt-Daroff exercises",
            "Avoid sudden head movements",
            "Sleep with head slightly elevated",
            "Move slowly when getting up from bed",
            "Stay hydrated and avoid caffeine"
        ],
        "products": [
            {"name": "Meclizine Anti-Vertigo Tablets", "url": "https://www.amazon.com/dp/B07Q5LQWSN", "type": "Anti-Vertigo"},
            {"name": "Vertigo Relief Supplement", "url": "https://www.amazon.com/dp/B07GGCN9V3", "type": "Supplement"},
            {"name": "Motion Sickness Bands", "url": "https://www.amazon.com/dp/B001F731N0", "type": "Relief"},
            {"name": "Orthopedic Wedge Pillow", "url": "https://www.amazon.com/dp/B00DTZPIZQ", "type": "Sleep Aid"}
        ],
        "when_to_see_doctor": "If vertigo is severe, persistent, or accompanied by hearing loss"
    },
    "AIDS": {
        "cure_advice": [
            "Take antiretroviral therapy (ART) exactly as prescribed",
            "Never skip doses of medication",
            "Maintain regular medical appointments",
            "Practice safe behaviors to prevent transmission",
            "Eat nutritious foods and exercise regularly"
        ],
        "products": [
            {"name": "Pill Organizer Weekly", "url": "https://www.amazon.com/dp/B07XV4WHVJ", "type": "Medication Aid"},
            {"name": "Immune Support Vitamins", "url": "https://www.amazon.com/dp/B00LUKBYI2", "type": "Supplement"},
            {"name": "Protein Supplement", "url": "https://www.amazon.com/dp/B00EMXK95E", "type": "Nutrition"},
            {"name": "Digital Health Tracker", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Tracking"}
        ],
        "when_to_see_doctor": "Regular monitoring is essential - follow your HIV specialist's schedule"
    },
    "Acne": {
        "cure_advice": [
            "Wash face twice daily with a gentle cleanser",
            "Use non-comedogenic moisturizers and sunscreen",
            "Apply benzoyl peroxide or salicylic acid treatments",
            "Avoid touching your face and popping pimples",
            "Change pillowcases frequently"
        ],
        "products": [
            {"name": "CeraVe Acne Foaming Cream Cleanser", "url": "https://www.amazon.com/dp/B08GWVLKK1", "type": "Cleanser"},
            {"name": "Differin Adapalene Gel 0.1%", "url": "https://www.amazon.com/dp/B07L1PHSY9", "type": "Retinoid"},
            {"name": "Paula's Choice 2% BHA Liquid", "url": "https://www.amazon.com/dp/B00949CTQQ", "type": "Exfoliant"},
            {"name": "Neutrogena Oil-Free Acne Wash", "url": "https://www.amazon.com/dp/B001E96ORK", "type": "Cleanser"}
        ],
        "when_to_see_doctor": "If acne is severe, painful, or leaving scars"
    },
    "Alcoholic hepatitis": {
        "cure_advice": [
            "Stop drinking alcohol completely - this is essential",
            "Follow a nutritious, balanced diet",
            "Take prescribed medications as directed",
            "Join alcohol recovery support groups",
            "Get adequate rest and avoid liver toxins"
        ],
        "products": [
            {"name": "Milk Thistle Liver Support", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "B-Complex Vitamins", "url": "https://www.amazon.com/dp/B07PFSQYG5", "type": "Vitamin"},
            {"name": "Liver Support Formula", "url": "https://www.amazon.com/dp/B07NY2XF1N", "type": "Supplement"},
            {"name": "Alcohol Recovery Journal", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Recovery Aid"}
        ],
        "when_to_see_doctor": "Immediately - alcoholic hepatitis requires medical treatment"
    },
    "Allergy": {
        "cure_advice": [
            "Identify and avoid known allergens",
            "Take antihistamines as needed for symptoms",
            "Keep windows closed during high pollen days",
            "Use HEPA air purifiers in your home",
            "Shower after outdoor activities"
        ],
        "products": [
            {"name": "Zyrtec 24 Hour Allergy Relief", "url": "https://www.amazon.com/dp/B074G2BKFG", "type": "Antihistamine"},
            {"name": "Flonase Allergy Relief Nasal Spray", "url": "https://www.amazon.com/dp/B00MXOV038", "type": "Nasal Spray"},
            {"name": "HEPA Air Purifier", "url": "https://www.amazon.com/dp/B07VVK39F7", "type": "Air Purifier"},
            {"name": "Allergen-Proof Pillow Covers", "url": "https://www.amazon.com/dp/B001JKV8B0", "type": "Bedding"}
        ],
        "when_to_see_doctor": "If symptoms are severe or don't respond to OTC medications"
    },
    "Arthritis": {
        "cure_advice": [
            "Stay physically active with low-impact exercises",
            "Apply hot or cold packs to affected joints",
            "Maintain a healthy weight to reduce joint stress",
            "Take anti-inflammatory medications as directed",
            "Consider physical therapy for mobility"
        ],
        "products": [
            {"name": "Voltaren Arthritis Pain Gel", "url": "https://www.amazon.com/dp/B08422YZXH", "type": "Topical Pain Relief"},
            {"name": "Glucosamine Chondroitin Supplement", "url": "https://www.amazon.com/dp/B0013OQEO8", "type": "Joint Supplement"},
            {"name": "Heating Pad for Pain Relief", "url": "https://www.amazon.com/dp/B00NWFJBPC", "type": "Heat Therapy"},
            {"name": "Compression Gloves for Arthritis", "url": "https://www.amazon.com/dp/B07D6K8HXJ", "type": "Support"}
        ],
        "when_to_see_doctor": "If joint pain is severe or affects daily activities"
    },
    "Bronchial Asthma": {
        "cure_advice": [
            "Use prescribed inhalers correctly and regularly",
            "Identify and avoid asthma triggers",
            "Keep rescue inhaler accessible at all times",
            "Monitor peak flow readings daily",
            "Create an asthma action plan with your doctor"
        ],
        "products": [
            {"name": "Portable Peak Flow Meter", "url": "https://www.amazon.com/dp/B0032B45C0", "type": "Monitor"},
            {"name": "HEPA Air Purifier for Allergies", "url": "https://www.amazon.com/dp/B07VVK39F7", "type": "Air Purifier"},
            {"name": "Inhaler Spacer Chamber", "url": "https://www.amazon.com/dp/B004IPDQ0S", "type": "Inhaler Aid"},
            {"name": "Dust Mite Proof Mattress Cover", "url": "https://www.amazon.com/dp/B0016GUHRE", "type": "Bedding"}
        ],
        "when_to_see_doctor": "If symptoms worsen or rescue inhaler needed more than twice weekly"
    },
    "Cervical spondylosis": {
        "cure_advice": [
            "Practice good posture especially when using devices",
            "Do gentle neck stretches and exercises daily",
            "Use ergonomic pillows for proper neck support",
            "Apply heat or cold therapy for pain relief",
            "Take breaks from prolonged sitting"
        ],
        "products": [
            {"name": "Cervical Memory Foam Pillow", "url": "https://www.amazon.com/dp/B07DLRFNT6", "type": "Neck Support"},
            {"name": "Neck Stretcher Device", "url": "https://www.amazon.com/dp/B07RXWM8KW", "type": "Therapy"},
            {"name": "Heating Pad for Neck Pain", "url": "https://www.amazon.com/dp/B07G9NNDHQ", "type": "Heat Therapy"},
            {"name": "Topical Pain Relief Cream", "url": "https://www.amazon.com/dp/B08422YZXH", "type": "Pain Relief"}
        ],
        "when_to_see_doctor": "If numbness in arms, weakness, or difficulty walking develops"
    },
    "Chicken pox": {
        "cure_advice": [
            "Keep skin clean and avoid scratching blisters",
            "Apply calamine lotion to soothe itching",
            "Take lukewarm baths with baking soda or oatmeal",
            "Take acetaminophen for fever (avoid aspirin)",
            "Rest and stay hydrated"
        ],
        "products": [
            {"name": "Calamine Lotion", "url": "https://www.amazon.com/dp/B000GCVIY6", "type": "Anti-Itch"},
            {"name": "Aveeno Soothing Bath Treatment", "url": "https://www.amazon.com/dp/B0009XNJHM", "type": "Bath Treatment"},
            {"name": "Anti-Itch Cream", "url": "https://www.amazon.com/dp/B06XS3SB7J", "type": "Relief"},
            {"name": "Soft Cotton Mittens", "url": "https://www.amazon.com/dp/B07TXP2BQK", "type": "Scratch Prevention"}
        ],
        "when_to_see_doctor": "If blisters become infected, high fever, or breathing difficulties"
    },
    "Chronic cholestasis": {
        "cure_advice": [
            "Follow prescribed medication regimen carefully",
            "Eat a low-fat diet with adequate nutrients",
            "Take prescribed ursodeoxycholic acid regularly",
            "Avoid alcohol completely",
            "Monitor for signs of worsening liver function"
        ],
        "products": [
            {"name": "Liver Support Supplement", "url": "https://www.amazon.com/dp/B07NY2XF1N", "type": "Supplement"},
            {"name": "Vitamin D3 Supplement", "url": "https://www.amazon.com/dp/B00LU2CD4A", "type": "Vitamin"},
            {"name": "Cholesterol Support Formula", "url": "https://www.amazon.com/dp/B00J8ETSF0", "type": "Supplement"},
            {"name": "Anti-Itch Cream for Jaundice", "url": "https://www.amazon.com/dp/B001F51A0M", "type": "Relief"}
        ],
        "when_to_see_doctor": "Regular monitoring required - follow hepatologist's schedule"
    },
    "Common Cold": {
        "cure_advice": [
            "Rest and get plenty of sleep",
            "Stay hydrated with water, tea, and clear broths",
            "Use saline nasal sprays for congestion",
            "Gargle with warm salt water for sore throat",
            "Use over-the-counter cold medications for symptoms"
        ],
        "products": [
            {"name": "DayQuil/NyQuil Cold & Flu Relief", "url": "https://www.amazon.com/dp/B07J279M9D", "type": "Cold Medicine"},
            {"name": "Mucinex Chest Congestion", "url": "https://www.amazon.com/dp/B000052X2P", "type": "Decongestant"},
            {"name": "Throat Lozenges with Zinc", "url": "https://www.amazon.com/dp/B0030BGBKS", "type": "Throat Relief"},
            {"name": "Vicks VapoRub", "url": "https://www.amazon.com/dp/B0064L9B1G", "type": "Topical Relief"}
        ],
        "when_to_see_doctor": "If symptoms last more than 10 days or fever exceeds 103°F"
    },
    "Dengue": {
        "cure_advice": [
            "Rest and drink plenty of fluids to prevent dehydration",
            "Take acetaminophen for fever and pain (avoid aspirin/ibuprofen)",
            "Monitor for warning signs of severe dengue",
            "Use mosquito repellent to prevent spread",
            "Seek immediate care if severe symptoms develop"
        ],
        "products": [
            {"name": "Oral Rehydration Salts", "url": "https://www.amazon.com/dp/B000LKYYSA", "type": "Hydration"},
            {"name": "Acetaminophen Pain Reliever", "url": "https://www.amazon.com/dp/B07NDPV4SL", "type": "Pain Relief"},
            {"name": "Mosquito Repellent with DEET", "url": "https://www.amazon.com/dp/B004H89KFC", "type": "Prevention"},
            {"name": "Electrolyte Drinks", "url": "https://www.amazon.com/dp/B001QW1L52", "type": "Hydration"}
        ],
        "when_to_see_doctor": "Immediately if severe abdominal pain, persistent vomiting, or bleeding"
    },
    "Diabetes ": {
        "cure_advice": [
            "Monitor blood sugar levels regularly",
            "Follow a balanced, low-glycemic diet",
            "Exercise regularly as approved by your doctor",
            "Take medications as prescribed",
            "Check feet daily for wounds or infections"
        ],
        "products": [
            {"name": "Blood Glucose Monitor Kit", "url": "https://www.amazon.com/dp/B08B3ZLNWM", "type": "Monitor"},
            {"name": "Diabetic Testing Strips", "url": "https://www.amazon.com/dp/B07MPXVMRF", "type": "Testing"},
            {"name": "Low-Glycemic Snack Bars", "url": "https://www.amazon.com/dp/B07NSDM1MS", "type": "Nutrition"},
            {"name": "Diabetic Foot Cream", "url": "https://www.amazon.com/dp/B001G7PZWG", "type": "Foot Care"}
        ],
        "when_to_see_doctor": "Regularly for monitoring; immediately if very high/low blood sugar"
    },
    "Dimorphic hemmorhoids(piles)": {
        "cure_advice": [
            "Eat high-fiber foods to prevent constipation",
            "Drink plenty of water throughout the day",
            "Avoid straining during bowel movements",
            "Take warm sitz baths for relief",
            "Use over-the-counter hemorrhoid creams"
        ],
        "products": [
            {"name": "Preparation H Hemorrhoid Cream", "url": "https://www.amazon.com/dp/B07JQ9Y2SJ", "type": "Treatment"},
            {"name": "Sitz Bath Basin", "url": "https://www.amazon.com/dp/B07N1B68YQ", "type": "Relief"},
            {"name": "Fiber Supplement Powder", "url": "https://www.amazon.com/dp/B0013I1D0M", "type": "Fiber"},
            {"name": "Hemorrhoid Cushion Pillow", "url": "https://www.amazon.com/dp/B07VSCQ4D5", "type": "Comfort"}
        ],
        "when_to_see_doctor": "If bleeding is heavy, pain is severe, or symptoms persist"
    },
    "Drug Reaction": {
        "cure_advice": [
            "Stop taking the suspected medication immediately",
            "Document the reaction and medication for your records",
            "Take antihistamines for mild allergic reactions",
            "Carry allergy alert information",
            "Inform all healthcare providers of the reaction"
        ],
        "products": [
            {"name": "Benadryl Antihistamine", "url": "https://www.amazon.com/dp/B0000AA2O1", "type": "Antihistamine"},
            {"name": "Hydrocortisone Cream 1%", "url": "https://www.amazon.com/dp/B001F51A0M", "type": "Anti-Itch"},
            {"name": "Medical Alert Bracelet", "url": "https://www.amazon.com/dp/B07G3DKTZ4", "type": "Alert"},
            {"name": "Medication Tracking Journal", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Tracking"}
        ],
        "when_to_see_doctor": "Immediately if difficulty breathing, swelling, or severe symptoms"
    },
    "Fungal infection": {
        "cure_advice": [
            "Keep affected area clean and dry",
            "Apply antifungal cream, powder, or spray",
            "Wear loose-fitting, breathable clothing",
            "Change socks and underwear daily",
            "Avoid sharing personal items like towels"
        ],
        "products": [
            {"name": "Lotrimin AF Antifungal Cream", "url": "https://www.amazon.com/dp/B00B2A1P3E", "type": "Antifungal"},
            {"name": "Lamisil AT Cream", "url": "https://www.amazon.com/dp/B00K2XT0NQ", "type": "Antifungal"},
            {"name": "Antifungal Body Powder", "url": "https://www.amazon.com/dp/B000052XUT", "type": "Powder"},
            {"name": "Tea Tree Oil", "url": "https://www.amazon.com/dp/B07L9BGML2", "type": "Natural"}
        ],
        "when_to_see_doctor": "If infection spreads, doesn't improve in 2 weeks, or affects nails"
    },
    "GERD": {
        "cure_advice": [
            "Avoid trigger foods like spicy, fatty, or acidic foods",
            "Eat smaller, more frequent meals",
            "Don't lie down for 2-3 hours after eating",
            "Elevate head of bed 6-8 inches",
            "Take antacids or prescribed medications as directed"
        ],
        "products": [
            {"name": "Prilosec OTC Acid Reducer", "url": "https://www.amazon.com/dp/B0756RMSMC", "type": "Antacid"},
            {"name": "Bed Wedge Pillow", "url": "https://www.amazon.com/dp/B00DTZPIZQ", "type": "Sleep Aid"},
            {"name": "TUMS Antacid Chewable Tablets", "url": "https://www.amazon.com/dp/B01M6ABKH4", "type": "Antacid"},
            {"name": "Gaviscon Extra Strength", "url": "https://www.amazon.com/dp/B01A97LK4W", "type": "Antacid"}
        ],
        "when_to_see_doctor": "If symptoms persist despite medication or difficulty swallowing"
    },
    "Gastroenteritis": {
        "cure_advice": [
            "Stay hydrated with small sips of clear fluids",
            "Use oral rehydration solutions for electrolytes",
            "Eat bland foods like rice, bananas, toast when able",
            "Rest and avoid dairy products initially",
            "Practice good hand hygiene to prevent spread"
        ],
        "products": [
            {"name": "Pedialyte Electrolyte Solution", "url": "https://www.amazon.com/dp/B001QW1L52", "type": "Hydration"},
            {"name": "Imodium Anti-Diarrheal", "url": "https://www.amazon.com/dp/B07NWNZFVR", "type": "Anti-Diarrheal"},
            {"name": "Pepto-Bismol", "url": "https://www.amazon.com/dp/B000052X2J", "type": "Stomach Relief"},
            {"name": "Probiotic Supplement", "url": "https://www.amazon.com/dp/B07DLRFM6V", "type": "Probiotic"}
        ],
        "when_to_see_doctor": "If severe dehydration, bloody stool, or symptoms last more than 3 days"
    },
    "Heart attack": {
        "cure_advice": [
            "CALL 911 IMMEDIATELY - this is a medical emergency",
            "Chew aspirin if not allergic (unless told not to)",
            "Rest in a comfortable position",
            "Follow all cardiac rehabilitation guidelines after treatment",
            "Take all prescribed medications without fail"
        ],
        "products": [
            {"name": "Aspirin 81mg Low Dose", "url": "https://www.amazon.com/dp/B07JQ37J5Q", "type": "Emergency"},
            {"name": "Blood Pressure Monitor", "url": "https://www.amazon.com/dp/B08DGT3VSZ", "type": "Monitor"},
            {"name": "Omega-3 Fish Oil Supplement", "url": "https://www.amazon.com/dp/B016YZUEWG", "type": "Heart Health"},
            {"name": "Heart Health Multivitamin", "url": "https://www.amazon.com/dp/B00LUKBYI2", "type": "Supplement"}
        ],
        "when_to_see_doctor": "IMMEDIATELY - call 911 for any heart attack symptoms"
    },
    "Hepatitis B": {
        "cure_advice": [
            "Take antiviral medications exactly as prescribed",
            "Avoid alcohol completely",
            "Get vaccinated against Hepatitis A if not immune",
            "Practice safe behaviors to prevent transmission",
            "Eat a healthy diet and get adequate rest"
        ],
        "products": [
            {"name": "Milk Thistle Liver Support", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "B-Complex Vitamins", "url": "https://www.amazon.com/dp/B07PFSQYG5", "type": "Vitamin"},
            {"name": "Liver Support Formula", "url": "https://www.amazon.com/dp/B07NY2XF1N", "type": "Supplement"},
            {"name": "Health Tracking Journal", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Tracking"}
        ],
        "when_to_see_doctor": "Regular monitoring required - follow hepatologist's schedule"
    },
    "Hepatitis C": {
        "cure_advice": [
            "Complete the full course of antiviral treatment",
            "Avoid alcohol completely",
            "Take medications at the same time daily",
            "Get tested for other hepatitis viruses",
            "Monitor liver function regularly"
        ],
        "products": [
            {"name": "Milk Thistle Supplement", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "Liver Support Complex", "url": "https://www.amazon.com/dp/B07NY2XF1N", "type": "Supplement"},
            {"name": "Pill Organizer", "url": "https://www.amazon.com/dp/B07XV4WHVJ", "type": "Medication Aid"},
            {"name": "Multivitamin for Liver Health", "url": "https://www.amazon.com/dp/B00LUKBYI2", "type": "Vitamin"}
        ],
        "when_to_see_doctor": "Regular monitoring essential during and after treatment"
    },
    "Hepatitis D": {
        "cure_advice": [
            "Hepatitis D only occurs with Hepatitis B - treat both",
            "Take antiviral medications as prescribed",
            "Avoid alcohol and liver-toxic substances",
            "Follow a healthy diet for liver support",
            "Get regular liver function tests"
        ],
        "products": [
            {"name": "Milk Thistle Liver Support", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "Liver Support Formula", "url": "https://www.amazon.com/dp/B07NY2XF1N", "type": "Supplement"},
            {"name": "B-Complex Vitamins", "url": "https://www.amazon.com/dp/B07PFSQYG5", "type": "Vitamin"},
            {"name": "Health Journal", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Tracking"}
        ],
        "when_to_see_doctor": "Regular monitoring is critical - follow specialist's schedule"
    },
    "Hepatitis E": {
        "cure_advice": [
            "Rest and hydrate - most cases resolve on their own",
            "Avoid alcohol and hepatotoxic medications",
            "Eat a balanced, nutritious diet",
            "Practice good hygiene to prevent spread",
            "Drink only clean, safe water"
        ],
        "products": [
            {"name": "Oral Rehydration Salts", "url": "https://www.amazon.com/dp/B000LKYYSA", "type": "Hydration"},
            {"name": "Milk Thistle Supplement", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "Water Purification Tablets", "url": "https://www.amazon.com/dp/B000HXYK7G", "type": "Water Safety"},
            {"name": "Multivitamin", "url": "https://www.amazon.com/dp/B00LUKBYI2", "type": "Vitamin"}
        ],
        "when_to_see_doctor": "If pregnant, have liver disease, or symptoms worsen"
    },
    "Hypertension ": {
        "cure_advice": [
            "Take blood pressure medications exactly as prescribed",
            "Reduce sodium intake in your diet",
            "Exercise regularly (as approved by doctor)",
            "Maintain a healthy weight",
            "Monitor blood pressure at home regularly"
        ],
        "products": [
            {"name": "Omron Blood Pressure Monitor", "url": "https://www.amazon.com/dp/B08DGT3VSZ", "type": "Monitor"},
            {"name": "Low-Sodium Seasonings", "url": "https://www.amazon.com/dp/B0009F2LG6", "type": "Diet Aid"},
            {"name": "CoQ10 Heart Health Supplement", "url": "https://www.amazon.com/dp/B005WUA31Q", "type": "Supplement"},
            {"name": "Potassium Supplement", "url": "https://www.amazon.com/dp/B002QWKJN0", "type": "Supplement"}
        ],
        "when_to_see_doctor": "Regularly for monitoring; immediately if very high readings"
    },
    "Hyperthyroidism": {
        "cure_advice": [
            "Take anti-thyroid medications as prescribed",
            "Avoid iodine-rich foods if advised",
            "Get adequate rest and manage stress",
            "Protect eyes if Graves' disease present",
            "Monitor heart rate and report rapid heartbeat"
        ],
        "products": [
            {"name": "Calcium + Vitamin D Supplement", "url": "https://www.amazon.com/dp/B002LC1L26", "type": "Supplement"},
            {"name": "Sunglasses for Light Sensitivity", "url": "https://www.amazon.com/dp/B07L4K9LQM", "type": "Eye Protection"},
            {"name": "Stress Relief Supplements", "url": "https://www.amazon.com/dp/B07DGNWFPL", "type": "Stress Relief"},
            {"name": "Heart Rate Monitor", "url": "https://www.amazon.com/dp/B08B1GL55S", "type": "Monitor"}
        ],
        "when_to_see_doctor": "Regularly for thyroid monitoring and medication adjustment"
    },
    "Hypoglycemia": {
        "cure_advice": [
            "Treat low blood sugar quickly with fast-acting glucose",
            "Eat regular meals and snacks throughout the day",
            "Carry glucose tablets or snacks at all times",
            "Wear medical identification",
            "Check blood sugar regularly"
        ],
        "products": [
            {"name": "Glucose Tablets Fast-Acting", "url": "https://www.amazon.com/dp/B00F3I6MEG", "type": "Emergency"},
            {"name": "Blood Glucose Monitor", "url": "https://www.amazon.com/dp/B08B3ZLNWM", "type": "Monitor"},
            {"name": "Medical Alert Bracelet", "url": "https://www.amazon.com/dp/B07G3DKTZ4", "type": "Safety"},
            {"name": "Portable Snack Container", "url": "https://www.amazon.com/dp/B07MQRKVH5", "type": "Storage"}
        ],
        "when_to_see_doctor": "If episodes are frequent or severe, or if causes are unknown"
    },
    "Hypothyroidism": {
        "cure_advice": [
            "Take levothyroxine exactly as prescribed",
            "Take medication on empty stomach, same time daily",
            "Wait 30-60 minutes before eating after medication",
            "Get regular thyroid function tests",
            "Be aware of symptoms of under/over treatment"
        ],
        "products": [
            {"name": "Selenium Supplement for Thyroid", "url": "https://www.amazon.com/dp/B0013OQEO8", "type": "Supplement"},
            {"name": "Vitamin B12 Supplement", "url": "https://www.amazon.com/dp/B007K6XKT4", "type": "Vitamin"},
            {"name": "Pill Organizer with Alarm", "url": "https://www.amazon.com/dp/B07XV4WHVJ", "type": "Medication Aid"},
            {"name": "Iodine Supplement", "url": "https://www.amazon.com/dp/B07RT1RTQZ", "type": "Supplement"}
        ],
        "when_to_see_doctor": "Every 6-12 months for monitoring; sooner if symptoms change"
    },
    "Impetigo": {
        "cure_advice": [
            "Apply prescribed antibiotic ointment as directed",
            "Keep affected areas clean and covered",
            "Wash hands frequently to prevent spread",
            "Don't share personal items like towels",
            "Complete full course of antibiotics if prescribed"
        ],
        "products": [
            {"name": "Bacitracin Antibiotic Ointment", "url": "https://www.amazon.com/dp/B000GCMHZQ", "type": "Topical"},
            {"name": "Hibiclens Antiseptic Cleanser", "url": "https://www.amazon.com/dp/B00CYXN86C", "type": "Cleanser"},
            {"name": "Non-Stick Sterile Bandages", "url": "https://www.amazon.com/dp/B0084HHHXW", "type": "Bandage"},
            {"name": "Antibacterial Hand Soap", "url": "https://www.amazon.com/dp/B0042VGNA0", "type": "Hygiene"}
        ],
        "when_to_see_doctor": "If sores spread, develop fever, or don't improve in 48 hours"
    },
    "Jaundice": {
        "cure_advice": [
            "Treat underlying cause as directed by doctor",
            "Rest and allow your body to recover",
            "Eat a healthy, balanced diet",
            "Stay hydrated",
            "Avoid alcohol and medications that stress the liver"
        ],
        "products": [
            {"name": "Milk Thistle Liver Support", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "B-Complex Vitamins", "url": "https://www.amazon.com/dp/B07PFSQYG5", "type": "Vitamin"},
            {"name": "Electrolyte Drinks", "url": "https://www.amazon.com/dp/B001QW1L52", "type": "Hydration"},
            {"name": "Digestive Enzyme Supplement", "url": "https://www.amazon.com/dp/B000GG2GQU", "type": "Digestive"}
        ],
        "when_to_see_doctor": "Immediately - jaundice indicates liver/blood issues requiring evaluation"
    },
    "Malaria": {
        "cure_advice": [
            "Take antimalarial medications exactly as prescribed",
            "Complete the full course of treatment",
            "Rest and stay hydrated",
            "Use acetaminophen for fever (avoid aspirin)",
            "Use mosquito nets and repellent during recovery"
        ],
        "products": [
            {"name": "Oral Rehydration Salts", "url": "https://www.amazon.com/dp/B000LKYYSA", "type": "Hydration"},
            {"name": "Mosquito Net for Bed", "url": "https://www.amazon.com/dp/B07QXDXV7P", "type": "Prevention"},
            {"name": "DEET Insect Repellent", "url": "https://www.amazon.com/dp/B004H89KFC", "type": "Prevention"},
            {"name": "Acetaminophen", "url": "https://www.amazon.com/dp/B07NDPV4SL", "type": "Fever Relief"}
        ],
        "when_to_see_doctor": "Immediately for diagnosis and treatment - malaria can be fatal"
    },
    "Migraine": {
        "cure_advice": [
            "Rest in a quiet, dark room during attacks",
            "Take pain relievers at first sign of migraine",
            "Keep a headache diary to identify triggers",
            "Stay hydrated and maintain regular sleep schedule",
            "Consider preventive medications if migraines are frequent"
        ],
        "products": [
            {"name": "Excedrin Migraine Pain Reliever", "url": "https://www.amazon.com/dp/B00JMV9AG8", "type": "Pain Relief"},
            {"name": "Ice Pack for Headaches", "url": "https://www.amazon.com/dp/B073P4MHGR", "type": "Cold Therapy"},
            {"name": "Migraine Relief Cap", "url": "https://www.amazon.com/dp/B07L5J3BLZ", "type": "Relief"},
            {"name": "Magnesium Supplement", "url": "https://www.amazon.com/dp/B00E0P4N7M", "type": "Prevention"}
        ],
        "when_to_see_doctor": "If migraines are severe, frequent, or pattern changes suddenly"
    },
    "Osteoarthristis": {
        "cure_advice": [
            "Stay active with low-impact exercises like swimming",
            "Maintain a healthy weight to reduce joint stress",
            "Use hot or cold therapy for pain relief",
            "Consider physical therapy for mobility",
            "Use assistive devices if needed for daily activities"
        ],
        "products": [
            {"name": "Voltaren Arthritis Pain Gel", "url": "https://www.amazon.com/dp/B08422YZXH", "type": "Pain Relief"},
            {"name": "Glucosamine Chondroitin Supplement", "url": "https://www.amazon.com/dp/B0013OQEO8", "type": "Joint Health"},
            {"name": "Knee Support Brace", "url": "https://www.amazon.com/dp/B07D6K8HXJ", "type": "Support"},
            {"name": "Electric Heating Pad", "url": "https://www.amazon.com/dp/B00NWFJBPC", "type": "Heat Therapy"}
        ],
        "when_to_see_doctor": "If pain limits daily activities or doesn't respond to treatment"
    },
    "Paralysis (brain hemorrhage)": {
        "cure_advice": [
            "CALL 911 IMMEDIATELY - this is a medical emergency",
            "Follow all rehabilitation therapy guidelines",
            "Take prescribed medications without fail",
            "Work with physical and occupational therapists",
            "Make home modifications for safety and accessibility"
        ],
        "products": [
            {"name": "Blood Pressure Monitor", "url": "https://www.amazon.com/dp/B08DGT3VSZ", "type": "Monitor"},
            {"name": "Mobility Walker with Wheels", "url": "https://www.amazon.com/dp/B01MSIXNKS", "type": "Mobility Aid"},
            {"name": "Bed Rail Safety Guard", "url": "https://www.amazon.com/dp/B0073S4QZU", "type": "Safety"},
            {"name": "Physical Therapy Resistance Bands", "url": "https://www.amazon.com/dp/B07F7RTWKC", "type": "Rehabilitation"}
        ],
        "when_to_see_doctor": "IMMEDIATELY for symptoms; regular follow-up for rehabilitation"
    },
    "Peptic ulcer diseae": {
        "cure_advice": [
            "Take prescribed medications (PPIs, antibiotics) as directed",
            "Avoid NSAIDs like aspirin and ibuprofen",
            "Quit smoking if applicable",
            "Limit alcohol and caffeine consumption",
            "Eat smaller, more frequent meals"
        ],
        "products": [
            {"name": "Prilosec OTC Acid Reducer", "url": "https://www.amazon.com/dp/B0756RMSMC", "type": "PPI"},
            {"name": "Antacid Chewable Tablets", "url": "https://www.amazon.com/dp/B01M6ABKH4", "type": "Antacid"},
            {"name": "Probiotic for Gut Health", "url": "https://www.amazon.com/dp/B07DLRFM6V", "type": "Probiotic"},
            {"name": "Digestive Enzyme Supplement", "url": "https://www.amazon.com/dp/B000GG2GQU", "type": "Digestive"}
        ],
        "when_to_see_doctor": "If symptoms worsen, vomiting blood, or black stools"
    },
    "Pneumonia": {
        "cure_advice": [
            "Take prescribed antibiotics exactly as directed",
            "Rest and get plenty of sleep",
            "Stay hydrated with water and warm fluids",
            "Use a humidifier to ease breathing",
            "Complete full course of antibiotics even if feeling better"
        ],
        "products": [
            {"name": "Cool Mist Humidifier", "url": "https://www.amazon.com/dp/B013IJPTFK", "type": "Humidifier"},
            {"name": "Pulse Oximeter", "url": "https://www.amazon.com/dp/B07PQ8WTC4", "type": "Monitor"},
            {"name": "Respiratory Relief Tea", "url": "https://www.amazon.com/dp/B00T74BJ2E", "type": "Relief"},
            {"name": "Vitamin C Supplement", "url": "https://www.amazon.com/dp/B000GG854O", "type": "Immune Support"}
        ],
        "when_to_see_doctor": "If difficulty breathing, chest pain, or symptoms worsen"
    },
    "Psoriasis": {
        "cure_advice": [
            "Keep skin moisturized with thick creams or ointments",
            "Use medicated shampoos containing coal tar or salicylic acid",
            "Apply topical corticosteroids during flare-ups",
            "Get moderate sunlight exposure (with doctor approval)",
            "Manage stress and avoid known triggers"
        ],
        "products": [
            {"name": "MG217 Psoriasis Cream", "url": "https://www.amazon.com/dp/B001G7QVGS", "type": "Treatment"},
            {"name": "Coal Tar Medicated Shampoo", "url": "https://www.amazon.com/dp/B00KGAZL3G", "type": "Shampoo"},
            {"name": "CeraVe Psoriasis Moisturizing Cream", "url": "https://www.amazon.com/dp/B07ZJP2MMZ", "type": "Moisturizer"},
            {"name": "Vitamin D3 Supplement", "url": "https://www.amazon.com/dp/B00LU2CD4A", "type": "Supplement"}
        ],
        "when_to_see_doctor": "If plaques cover large areas or joint pain develops"
    },
    "Tuberculosis": {
        "cure_advice": [
            "Take ALL TB medications exactly as prescribed",
            "Complete the full 6-9 month treatment course",
            "Allow healthcare workers to monitor treatment",
            "Cover mouth when coughing and wear mask",
            "Stay home from work/school until no longer contagious"
        ],
        "products": [
            {"name": "N95 Respirator Masks", "url": "https://www.amazon.com/dp/B08NXCRFQL", "type": "Protection"},
            {"name": "Vitamin D3 Supplement", "url": "https://www.amazon.com/dp/B00LU2CD4A", "type": "Immune Support"},
            {"name": "Pill Organizer Weekly", "url": "https://www.amazon.com/dp/B07XV4WHVJ", "type": "Medication Aid"},
            {"name": "High-Protein Nutrition Supplement", "url": "https://www.amazon.com/dp/B00EMXK95E", "type": "Nutrition"}
        ],
        "when_to_see_doctor": "Regularly throughout treatment - compliance is critical"
    },
    "Typhoid": {
        "cure_advice": [
            "Take prescribed antibiotics for the full course",
            "Rest and stay hydrated",
            "Eat small, frequent, bland meals",
            "Practice strict hygiene to prevent spread",
            "Don't prepare food for others until cleared"
        ],
        "products": [
            {"name": "Oral Rehydration Solution", "url": "https://www.amazon.com/dp/B000LKYYSA", "type": "Hydration"},
            {"name": "Probiotic Supplement", "url": "https://www.amazon.com/dp/B07DLRFM6V", "type": "Gut Health"},
            {"name": "Digital Thermometer", "url": "https://www.amazon.com/dp/B07YK7SDQR", "type": "Monitor"},
            {"name": "Antibacterial Hand Soap", "url": "https://www.amazon.com/dp/B0042VGNA0", "type": "Hygiene"}
        ],
        "when_to_see_doctor": "Immediately for treatment; complications can be serious"
    },
    "Urinary tract infection": {
        "cure_advice": [
            "Take prescribed antibiotics for the full course",
            "Drink plenty of water to flush bacteria",
            "Urinate frequently - don't hold it",
            "Wipe front to back to prevent bacteria spread",
            "Avoid irritants like caffeine and alcohol"
        ],
        "products": [
            {"name": "AZO Urinary Pain Relief", "url": "https://www.amazon.com/dp/B000052Y49", "type": "Pain Relief"},
            {"name": "Cranberry Supplement Capsules", "url": "https://www.amazon.com/dp/B01LSFQ4DS", "type": "Prevention"},
            {"name": "D-Mannose Supplement", "url": "https://www.amazon.com/dp/B00SWGM8LY", "type": "Prevention"},
            {"name": "Probiotic for Women", "url": "https://www.amazon.com/dp/B07DLRFM6V", "type": "Health"}
        ],
        "when_to_see_doctor": "If symptoms persist, worsen, or fever develops"
    },
    "Varicose veins": {
        "cure_advice": [
            "Wear compression stockings during the day",
            "Elevate legs when resting",
            "Exercise regularly to improve circulation",
            "Avoid prolonged standing or sitting",
            "Maintain a healthy weight"
        ],
        "products": [
            {"name": "Medical Compression Stockings", "url": "https://www.amazon.com/dp/B07CMM4HL5", "type": "Compression"},
            {"name": "Leg Elevation Pillow", "url": "https://www.amazon.com/dp/B07H96GKF3", "type": "Elevation"},
            {"name": "Horse Chestnut Supplement", "url": "https://www.amazon.com/dp/B000UDD3TO", "type": "Supplement"},
            {"name": "Cooling Leg Gel", "url": "https://www.amazon.com/dp/B07RBTT8FV", "type": "Relief"}
        ],
        "when_to_see_doctor": "If veins become painful, swelling occurs, or skin changes develop"
    },
    "hepatitis A": {
        "cure_advice": [
            "Rest and allow your body to recover",
            "Drink plenty of fluids to prevent dehydration",
            "Eat small, nutritious meals throughout the day",
            "Avoid alcohol completely during recovery",
            "Practice good hygiene to prevent spread"
        ],
        "products": [
            {"name": "Electrolyte Drinks", "url": "https://www.amazon.com/dp/B001QW1L52", "type": "Hydration"},
            {"name": "Milk Thistle Liver Support", "url": "https://www.amazon.com/dp/B00CQ7PXAG", "type": "Supplement"},
            {"name": "B-Complex Vitamins", "url": "https://www.amazon.com/dp/B07PFSQYG5", "type": "Vitamin"},
            {"name": "Hand Sanitizer", "url": "https://www.amazon.com/dp/B08CSBQN21", "type": "Hygiene"}
        ],
        "when_to_see_doctor": "For diagnosis and if symptoms worsen or jaundice develops"
    }
}


# Default cure advice for unknown diseases
DEFAULT_CURE_INFO = {
    "cure_advice": [
        "Consult with a healthcare professional for proper diagnosis",
        "Follow prescribed treatment plans carefully",
        "Maintain a healthy lifestyle with proper nutrition",
        "Get adequate rest and stay hydrated",
        "Monitor symptoms and report any changes to your doctor"
    ],
    "products": [
        {"name": "Digital Thermometer", "url": "https://www.amazon.com/dp/B07YK7SDQR", "type": "Health Monitor"},
        {"name": "Pulse Oximeter", "url": "https://www.amazon.com/dp/B07PQ8WTC4", "type": "Health Monitor"},
        {"name": "First Aid Kit", "url": "https://www.amazon.com/dp/B000069EYA", "type": "Emergency"},
        {"name": "Health Journal", "url": "https://www.amazon.com/dp/B07PZLHMJ3", "type": "Tracking"}
    ],
    "when_to_see_doctor": "If symptoms persist or worsen"
}


def get_ai_cure_assistance(disease: str) -> dict:
    """
    AI Agent function to provide cure assistance and product recommendations
    for detected diseases.

    Args:
        disease: The predicted disease name

    Returns:
        Dictionary containing:
        - cure_advice: List of actionable cure/treatment advice
        - products: List of product recommendations with links
        - when_to_see_doctor: Guidance on when to seek medical help
        - ai_note: Disclaimer about AI-generated advice
    """
    # Normalize disease name for matching
    disease_stripped = disease.strip()
    disease_lower = disease_stripped.lower()
    
    # Build a case-insensitive lookup dictionary
    disease_lookup = {k.lower().strip(): v for k, v in DISEASE_CURE_DATABASE.items()}
    
    # Try exact match first (case-insensitive)
    cure_info = disease_lookup.get(disease_lower, None)
    
    # If not found, try exact match with original case (handles trailing spaces)
    if cure_info is None:
        cure_info = DISEASE_CURE_DATABASE.get(disease_stripped, None)
    
    # Try matching with trailing space (some diseases have trailing spaces like "Diabetes ")
    if cure_info is None:
        cure_info = DISEASE_CURE_DATABASE.get(disease_stripped + " ", None)
        if cure_info is None:
            cure_info = disease_lookup.get(disease_lower + " ", None)
    
    # If not found, try partial matching
    if cure_info is None:
        # Common words to exclude from matching
        stop_words = {'disease', 'infection', 'disorder', 'syndrome', 'unknown', 'the', 'and', 'or'}
        
        for db_disease, info in DISEASE_CURE_DATABASE.items():
            db_lower = db_disease.lower().strip()
            # Check if one contains the other (but skip very short input)
            if len(disease_lower) > 4:
                if db_lower in disease_lower or disease_lower in db_lower:
                    cure_info = info
                    break
            # Check for key word matching (e.g., "Fungal" matches "Fungal infection")
            disease_words = set(disease_lower.replace("_", " ").split()) - stop_words
            db_words = set(db_lower.replace("_", " ").split()) - stop_words
            if disease_words & db_words:  # If there's word overlap
                common_words = disease_words & db_words
                # Require at least one significant word match (not just short words)
                if any(len(w) > 4 for w in common_words):
                    cure_info = info
                    break
    
    # If still not found, use default advice
    if cure_info is None:
        cure_info = DEFAULT_CURE_INFO.copy()
    
    return {
        "cure_advice": cure_info.get("cure_advice", DEFAULT_CURE_INFO["cure_advice"]),
        "products": cure_info.get("products", DEFAULT_CURE_INFO["products"]),
        "when_to_see_doctor": cure_info.get("when_to_see_doctor", DEFAULT_CURE_INFO["when_to_see_doctor"]),
        "ai_note": "⚠️ This advice is AI-generated for educational purposes only. Always consult a qualified healthcare professional before starting any treatment."
    }
